server:
  port: 8080

spring:
  application:
    name: "Jobs Tracker API"
  profiles:
    active: prod
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

---

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/myjobs
    username: postgres
    password: postgres
  config:
    activate:
      on-profile: dev
    use-legacy-processing: true

---

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?user=${DATABASE_USERNAME}&password=${DATABASE_PASSWORD}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  config:
    activate:
      on-profile: prod